source 'https://rubygems.org'


gem 'rails', '4.2.0'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem "paperclip", :git => "git://github.com/thoughtbot/paperclip.git"
gem 'devise'
gem 'omniauth-facebook'
gem 'ransack'
gem 'capybara'
gem 'factory_girl_rails'
gem 'will_paginate', '~> 3.0.6'
gem 'acts-as-taggable-on'
group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring', "~> 1.3.6"
  gem 'rspec-rails', '~> 3.0'
end

