# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a67edeee0b69c33e8ad062d9d373366dfd1c629ce89625e5f18b2c89ee94c181e09bdb8703a3d37cf95b39d83355ad5130ba06e7b00605ebc608a5214fde0925

test:
  secret_key_base: 6706b0145886bee4fe1f24a952204872da534a0970bc1e18ef4747b38ebff0707a20d9b640c179914659efab21daec2212ff6c5587be31d0a9b68805fc62ccc9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
